name: 🚀 Deploy manually to doubledeals & infinityfree 

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # Deploy to delta.doubledeals.co.ke
  deploy-to-delta:
    name: 🎉 Deploy to Delta DoubleDeals
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files to Delta DoubleDeals
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # server: ${{ secrets.FTP_SERVER }}
          # username: ${{ secrets.FTP_USERNAME }}
          # password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /  # The directory on the server to deploy files to

  # Deploy to InfinityFree
  deploy-to-infinityfree:
    name: 🎉 Deploy to InfinityFree
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # server: ftpupload.net
          # username: if0_37114096
          # password: QcIDYuIrKJ # Store sensitive data in GitHub Secrets
          # server-dir: htdocs/
          # retries: 3                 # Retry the connection up to 3 times in case of timeout
          # retryDelay: 10             # Wait 10 seconds before retrying after a failure
